<script setup>
import { reactive, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { api } from '../../api/index.js'
const form = reactive({ orderId: 0, productId: 0, rating: 5, content: '', images: [] }); const product = ref(null)
onLoad(async (query) => { form.orderId = Number(query.orderId); form.productId = Number(query.productId); product.value = await api.getProduct(form.productId) })
async function submit() { if (!form.content.trim()) return uni.showToast({ title: '说说你的使用感受吧', icon: 'none' }); await api.createReview(form); uni.showToast({ title: '评价成功' }); setTimeout(() => uni.navigateBack(), 300) }
function chooseImages() { uni.chooseImage({ count: 6 - form.images.length, success: async ({ tempFilePaths }) => { for (const path of tempFilePaths) { const file = await api.uploadImage(path); form.images.push(file.url) } } }) }
</script>
<template><view class="page review-page"><view v-if="product" class="product"><image :src="product.mainImage" mode="aspectFill" /><text>{{ product.name }}</text></view><view class="rating"><text>商品评分</text><view><text v-for="n in 5" :key="n" :class="{ on: n === form.rating }" @tap="form.rating = n">{{ n }}分</text></view></view><textarea v-model="form.content" class="content" maxlength="500" placeholder="商品是否符合期待？分享你的体验，帮助更多人做选择。" /><view class="photos"><image v-for="url in form.images" :key="url" :src="url" mode="aspectFill" /><button v-if="form.images.length < 6" @tap="chooseImages">添加图片</button></view><button class="primary-button" @tap="submit">提交评价</button></view></template>
<style scoped>.review-page { padding: 24rpx; }.product,.rating,.content,.photos { background: #fff; border-radius: 20rpx; }.product { padding: 22rpx; display: flex; align-items: center; gap: 20rpx; }.product image { width: 120rpx; height: 120rpx; border-radius: 12rpx; }.rating { margin-top: 20rpx; padding: 28rpx; }.rating > text { display: block; margin-bottom: 20rpx; }.rating view { display: flex; gap: 10rpx; }.rating view text { padding: 10rpx 18rpx; border-radius: 999rpx; background: #f3f3f3; color: #777; font-size: 23rpx; }.rating .on { background: var(--brand); color: #fff; }.content { width: 100%; min-height: 300rpx; margin-top: 20rpx; padding: 26rpx; font-size: 28rpx; }.photos { margin-top: 20rpx; padding: 22rpx; display: flex; flex-wrap: wrap; gap: 16rpx; }.photos image,.photos button { width: 144rpx; height: 144rpx; margin: 0; border-radius: 12rpx; }.photos button { color: var(--muted); background: #f5f5f5; font-size: 23rpx; line-height: 144rpx; }.photos button::after { border: 0; }.review-page > button { margin-top: 40rpx; }</style>
