<script setup>
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { api } from '../../api/index.js'
import { formatPrice, formatDate } from '../../utils/format.js'
import { getOrderActions, getOrderStatus } from '../../utils/order.js'
const order = ref(null); const actions = computed(() => order.value ? getOrderActions(order.value.status) : [])
const labels = { pay: '立即支付', cancel: '取消订单', confirm: '确认收货', review: '评价', refund: '申请售后' }
async function load(id) { order.value = await api.getOrder(id) }
async function act(action) { if (action === 'review') return uni.navigateTo({ url: `/pages/review/create?orderId=${order.value.id}&productId=${order.value.items[0].productId}` }); if (action === 'refund') return uni.navigateTo({ url: `/pages/refund/create?orderId=${order.value.id}` }); try { if (action === 'pay') await api.payOrder(order.value.id); if (action === 'cancel') await api.cancelOrder(order.value.id); if (action === 'confirm') await api.confirmOrder(order.value.id); await load(order.value.id); uni.showToast({ title: '操作成功' }) } catch (error) { uni.showToast({ title: error.message, icon: 'none' }) } }
onLoad((query) => load(query.id))
</script>
<template><view v-if="order" class="page detail-page"><view class="status-block"><text class="status">{{ getOrderStatus(order.status).text }}</text><text>感谢选择悦选，我们会及时同步订单进度</text></view><view class="address"><text>{{ order.address?.name }}　{{ order.address?.phone }}</text><text class="muted">{{ order.address?.province }}{{ order.address?.city }}{{ order.address?.district }}{{ order.address?.detail }}</text></view><view class="goods"><view class="merchant">{{ order.merchantName }}</view><view v-for="item in order.items" :key="item.skuId" class="item"><image :src="item.image" mode="aspectFill" /><view class="grow"><text>{{ item.name }}</text><text class="muted">{{ item.skuName }}</text></view><text>¥{{ formatPrice(item.price) }} ×{{ item.quantity }}</text></view><view class="money">订单金额 <text>¥{{ formatPrice(order.totalAmount) }}</text></view></view><view class="meta"><text>订单编号　{{ order.orderNo }}</text><text>创建时间　{{ formatDate(order.createdAt) }}</text><text v-if="order.remark">订单备注　{{ order.remark }}</text></view><view v-if="actions.length" class="bottom-action actions"><button v-for="action in actions" :key="action" :class="action === 'pay' ? 'primary-button' : 'secondary-button'" @tap="act(action)">{{ labels[action] }}</button></view></view></template>
<style scoped>.detail-page { padding: 0 24rpx 140rpx; }.status-block { margin: 0 -24rpx; padding: 48rpx 28rpx; background: var(--brand); color: #fff; display: flex; flex-direction: column; gap: 14rpx; font-size: 25rpx; }.status { font-size: 38rpx; font-weight: 700; }.address,.goods,.meta { margin-top: 20rpx; padding: 24rpx; border-radius: 20rpx; background: #fff; }.address,.meta { display: flex; flex-direction: column; gap: 12rpx; font-size: 25rpx; }.merchant { padding-bottom: 20rpx; font-weight: 650; }.item { display: flex; gap: 16rpx; padding: 20rpx 0; border-top: 2rpx solid var(--line); font-size: 24rpx; }.item image { width: 140rpx; height: 140rpx; border-radius: 12rpx; }.grow { flex: 1; display: flex; flex-direction: column; gap: 12rpx; }.money { padding-top: 20rpx; text-align: right; }.money text { margin-left: 30rpx; color: var(--brand); font-weight: 650; }.actions { display: flex; justify-content: flex-end; gap: 14rpx; }.actions button { width: 210rpx; line-height: 72rpx; }
</style>
