<script setup>
import { computed } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { useUserStore } from '../../stores/user.js'
const user = useUserStore(); const profile = computed(() => user.profile)
const orderLinks = [{ label: '待付款', status: 0 }, { label: '待发货', status: 1 }, { label: '待收货', status: 2 }, { label: '已完成', status: 4 }]
const menu = [{ label: '收货地址', url: '/pages/address/list' }, { label: '退款售后', url: '/pages/refund/list' }, { label: '编辑资料', url: '/pages/profile/edit' }, { label: '修改密码', url: '/pages/profile/password' }, { label: '商家入驻', url: '/pages/profile/merchant-apply' }]
function open(url) { if (!user.isLoggedIn) return uni.navigateTo({ url: '/pages/auth/login' }); uni.navigateTo({ url }) }
onShow(() => user.refreshProfile())
</script>
<template><view class="page profile-page"><view class="hero" @tap="!user.isLoggedIn && open('/pages/auth/login')"><view class="avatar">{{ profile?.nickname?.slice(0, 1) || '悦' }}</view><view><text class="nickname">{{ profile?.nickname || '登录 / 注册' }}</text><text class="muted">{{ profile?.phone || '登录后管理订单与权益' }}</text></view></view><view class="orders"><view class="orders-head"><text>我的订单</text><text class="muted" @tap="open('/pages/order/list')">全部订单 ›</text></view><view class="order-grid"><view v-for="item in orderLinks" :key="item.status" @tap="open(`/pages/order/list?status=${item.status}`)"><text class="dot"></text><text>{{ item.label }}</text></view></view></view><view class="menu"><view v-for="item in menu" :key="item.url" class="menu-line" @tap="open(item.url)"><text>{{ item.label }}</text><text class="muted">›</text></view></view><button v-if="user.isLoggedIn" class="logout" @tap="user.logout()">退出登录</button></view></template>
<style scoped>.profile-page { padding: 28rpx 24rpx; }.hero { min-height: 190rpx; padding: 34rpx; border-radius: 26rpx; background: #fff; display: flex; align-items: center; gap: 24rpx; }.avatar { width: 112rpx; height: 112rpx; border-radius: 50%; background: var(--soft-red); color: var(--brand); display: flex; align-items: center; justify-content: center; font-size: 46rpx; font-weight: 700; }.nickname { display: block; margin-bottom: 12rpx; font-size: 36rpx; font-weight: 700; }.orders,.menu { margin-top: 20rpx; background: #fff; border-radius: 20rpx; }.orders { padding: 24rpx; }.orders-head { display: flex; justify-content: space-between; }.order-grid { display: grid; grid-template-columns: repeat(4,1fr); margin-top: 30rpx; }.order-grid view { text-align: center; font-size: 25rpx; }.dot { display: block; width: 38rpx; height: 38rpx; margin: 0 auto 12rpx; border: 6rpx solid var(--brand); border-radius: 50%; }.menu { overflow: hidden; }.menu-line { min-height: 92rpx; padding: 0 26rpx; display: flex; align-items: center; justify-content: space-between; border-bottom: 2rpx solid var(--line); }.logout { margin-top: 36rpx; color: var(--brand); background: #fff; font-size: 28rpx; }</style>
