<script setup>
import { reactive } from 'vue'
import { api } from '../../api/index.js'
const form = reactive({ merchantName: '', contactName: '', contactPhone: '', businessLicense: '', licenseImage: '', description: '' })
function chooseLicense() { uni.chooseImage({ count: 1, success: async ({ tempFilePaths }) => { const file = await api.uploadImage(tempFilePaths[0]); form.licenseImage = file.url } }) }
async function submit() { if (!form.merchantName || !form.contactName || !/^1\d{10}$/.test(form.contactPhone)) return uni.showToast({ title: '请完整填写店铺与联系人信息', icon: 'none' }); await api.applyMerchant(form); uni.showModal({ title: '提交成功', content: '平台将在 1–3 个工作日内完成审核。', showCancel: false, success: () => uni.navigateBack() }) }
</script>
<template><view class="page apply-page"><view class="intro"><text class="title">在悦选，遇见更多好生意</text><text>提交基础资料后进入平台审核，本页仅提供 B 角色申请入口。</text></view><view class="surface form"><view class="form-field"><text>店铺名称</text><input v-model="form.merchantName" /></view><view class="form-field"><text>联系人</text><input v-model="form.contactName" /></view><view class="form-field"><text>联系电话</text><input v-model="form.contactPhone" type="number" maxlength="11" /></view><view class="form-field"><text>执照编号</text><input v-model="form.businessLicense" /></view><view class="upload" @tap="chooseLicense"><image v-if="form.licenseImage" :src="form.licenseImage" mode="aspectFit" /><text v-else>上传营业执照图片</text></view><view class="form-field textarea"><text>店铺简介</text><textarea v-model="form.description" /></view></view><button class="primary-button" @tap="submit">提交申请</button></view></template>
<style scoped>.apply-page { padding: 24rpx; }.intro { padding: 34rpx 28rpx; margin-bottom: 20rpx; border-radius: 20rpx; background: var(--soft-red); color: #744; }.intro text { display: block; line-height: 1.6; }.intro .title { margin-bottom: 8rpx; color: var(--brand); font-size: 34rpx; font-weight: 700; }.form { border-radius: 20rpx; overflow: hidden; }.upload { min-height: 180rpx; padding: 24rpx 28rpx; display: flex; align-items: center; justify-content: center; border-bottom: 2rpx solid var(--line); color: var(--muted); }.upload image { width: 240rpx; height: 160rpx; }.textarea { min-height: 180rpx; align-items: flex-start; padding-top: 28rpx; }.apply-page button { margin-top: 38rpx; }</style>
